language: node_js
node_js:
- '11'
cache:
  directories:
  - node_modules
after_success:
- npm run build
deploy:
  provider: npm
  email: pedrogp9693@gmail.com
  api_key: ${NPM_TOKEN}
  on:
    tags: true
    repo: Pedro-vk/ipfs-website-deployer
